#!/bin/bash
set -ex

if [ -d /boot/efi ];then
	mkdir -p /boot/efi/base
	mkdir -p /boot/efi/overlays
	cp /usr/lib/linux-image-*/rockchip/*.dtb /boot/efi/base
	cp /usr/lib/linux-image-*/rockchip/rockchip-rk3588-panthor-gpu.dtbo /boot/efi/overlays
fi
